addons:
  artifacts:
    debug: true
    paths: [libs.zip, build.zip]
    target_paths: 80fbd5e7-25b5-4cd0-a78f-cac388491126
after_success: ['mvn clean test jacoco:report coveralls:report', ./df-build.sh]
branches:
  only: [trunk]
jdk: [openjdk6, openjdk7, oraclejdk8]
language: java
sudo: false
# Modified by Insights Service at 2016-01-15 18:55:26.540176
